services:
  postgres:
    image: docker.io/postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: record_verifier_dev
    ports:
      - "5432:5432"
